name: Build and upload to PyPI

on:
  push:
    tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build sdist
        run: pipx run build --sdist

      - name: Test sdist
        run: |
          python -m pip install dist/apngasm_python-*.tar.gz
          pip install pytest numpy Pillow
          pytest

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/apngasm_python-*.tar.gz
          retention-days: 7

  build_wheels:
    name: Build wheels for ${{ matrix.os }} ${{ matrix.cibw_archs }} ${{ matrix.cibw_build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            cibw_archs: AMD64
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=x86_64
            artifact: win-amd64-cp_pp
          - os: windows-2019
            cibw_archs: x86
            cibw_build: "cp*"
            cibw_environment: APNGASM_COMPILE_TARGET=x86
            artifact: win-x86-cp
          - os: windows-2019
            cibw_archs: ARM64
            cibw_build: "cp*"
            cibw_environment: APNGASM_COMPILE_TARGET=armv8
            artifact: win-amrm64-cp
          - os: macos-13
            cibw_archs: x86_64
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=x86_64
            artifact: macos-x86_64-cp_pp
          - os: macos-14
            cibw_archs: arm64
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=armv8
            artifact: macos-arm64-cp_pp
          - os: macos-14
            cibw_archs: universal2
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=universal2
            artifact: macos-universal2-cp_pp
          - os: ubuntu-22.04
            cibw_archs: x86_64
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=x86_64
            artifact: many_musllinux-x86_64-cp_pp
          - os: ubuntu-22.04
            cibw_archs: i686
            cibw_build: "cp* pp*"
            cibw_environment: APNGASM_COMPILE_TARGET=x86
            artifact: many_musllinux-x86-cp_pp
          - os: ubuntu-22.04-arm
            cibw_archs: aarch64
            cibw_build: "cp*-musllinux_* pp*-musllinux_*"
            cibw_environment: APNGASM_COMPILE_TARGET=armv8
            artifact: musllinux-armv8-cp_pp
          - os: ubuntu-22.04-arm
            cibw_archs: aarch64
            cibw_build: "cp*-manylinux_* pp*-manylinux_*"
            cibw_environment: APNGASM_COMPILE_TARGET=armv8
            artifact: manylinux-armv8-cp_pp
          - os: ubuntu-22.04
            cibw_archs: ppc64le
            cibw_build: "cp*-musllinux_*"
            cibw_environment: APNGASM_COMPILE_TARGET=ppc64le
            artifact: musllinux-ppc64le-cp
          - os: ubuntu-22.04
            cibw_archs: ppc64le
            cibw_build: "cp*-manylinux_*"
            cibw_environment: APNGASM_COMPILE_TARGET=ppc64le
            artifact: manylinux-ppc64le-cp
          # - os: ubuntu-20.04
          #   cibw_archs: s390x
          #   cibw_build: "*-musllinux_*"
          #   cibw_environment: APNGASM_COMPILE_TARGET=s390x
          # - os: ubuntu-20.04
          #   cibw_archs: s390x
          #   cibw_build: "*-manylinux_*"
          #   cibw_environment: APNGASM_COMPILE_TARGET=s390x
            
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels for ${{ matrix.os }} ${{ matrix.cibw_archs }} ${{ matrix.cibw_build }}
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          # CIBW_ENVIRONMENT: PY_BUILD_CMAKE_VERBOSE=1 ${{ matrix.cibw_environment }}
          CIBW_ENVIRONMENT: ${{ matrix.cibw_environment }}
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST: pip install --only-binary ":all:" Pillow numpy; true
          CIBW_BEFORE_TEST_WINDOWS: pip install --only-binary ":all:" Pillow numpy || VER>NUL
          CIBW_TEST_COMMAND: pytest {package}/tests
          CIBW_TEST_SKIP: pp*
      
      - name: abi3audit
        run: |
          pip install abi3audit
          abi3audit $(ls ./wheelhouse/*.whl) --debug --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{matrix.artifact}}
          path: ./wheelhouse/*.whl
          retention-days: 7

  # upload_pypi_test:
  #   needs: [build_wheels, build_sdist]
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - name: "Download artifacts"
  #       uses: actions/download-artifact@v4
      
  #     - name: "Move packages to the dist/ folder"
  #       run: |
  #         mkdir dist/
  #         mv sdist/* dist/
  #         mv wheels-*/*.whl dist/

  #     - name: "Publish packages on PyPI"
  #       uses: pypa/gh-action-pypi-publish@v1.5.0
  #       with:
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
      
      - name: "Move packages to the dist/ folder"
        run: |
          mkdir dist/
          mv sdist/* dist/
          mv wheels-*/*.whl dist/

      - name: "Publish packages on PyPI"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}